# Generated by Django 3.2.9 on 2021-12-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
