# Generated by Django 3.2.9 on 2021-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20211221_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.FloatField(default=100),
        ),
    ]
